// 📌 아이템 도트 아이콘 — 16×16 픽셀 한 벌. 클라이언트·서버·node 공용 순수 JS(React·DOM 의존 없음).
//    icon 값이 "art:<key>" 면 ItemIcon 이 이 그림을 그린다. 목록은 ITEM_ARTS 하나 — lib/items.js 검증도 이걸 본다.
//    그림 규칙(게임 인벤토리 아이템 결):
//    · 아이콘마다 16줄 × 16글자 지도 + 글자→색 표. "." 은 투명
//    · 빛은 왼쪽 위. 음영은 같은 계열 램프(1 어두움 · 2 보통 · 3 밝음 · 4 빛)로 — 어두울수록 푸른·보랏빛, 밝을수록 따뜻하게
//    · 외곽선은 순검정 대신 물체 색의 0단계, 빛 받는 위·왼쪽 테두리는 1단계(sel-out). 속 경계선은 줄여 덩어리로 읽히게
//    · 재질 반사광: 유리·쇠는 흰 점·흰 줄 1~2칸, 반대편에 작은 반사 하나
//    · 색은 아래 공용 팔레트(ART_PALETTE)에서만, 아이콘당 10색 이내 — 그라데이션·흐림·반투명 금지
//    · 가로로 이어지는 같은 색 칸은 <rect> 하나로 묶고 shape-rendering="crispEdges"
//    · 화면에는 정수 배율(16·32·48…)로만 그린다 — 크기 맞춤은 ItemIcon 이 한다

export const ART_PREFIX = "art:";
// 격자 한 변(칸 수)
export const ART_GRID = 16;

// 묶음 — 아이콘 고르기 화면이 이 순서로 나눠 보여 준다
export const ITEM_ART_GROUPS = [
  { g: "item", label: "아이템" },
  { g: "time", label: "시간대" },
  { g: "day", label: "요일" },
  { g: "channel", label: "채널" },
  { g: "attend", label: "출석" },
  { g: "bundle", label: "묶음" },
  { g: "effect", label: "효과" },
];

export const ITEM_ARTS = [
  { key: "xp-potion", label: "XP 물약", group: "item" },
  { key: "attend-potion", label: "출석 물약", group: "item" },
  { key: "music-ticket", label: "음악 티켓", group: "item" },
  { key: "slowmode-off", label: "슬로우 해제", group: "item" },
  { key: "owl-charm", label: "올빼미 부적", group: "time" },
  { key: "early-bird", label: "얼리버드", group: "time" },
  { key: "lunch-box", label: "도시락", group: "time" },
  { key: "radio", label: "라디오", group: "time" },
  { key: "night-lantern", label: "등불", group: "time" },
  { key: "weekend-sword", label: "검과 방패", group: "day" },
  { key: "friday-fire", label: "불꽃", group: "day" },
  { key: "monday-vaccine", label: "백신", group: "day" },
  { key: "wednesday-coffee", label: "커피", group: "day" },
  { key: "scrim-mic", label: "금빛 마이크", group: "channel" },
  { key: "chat-megaphone", label: "확성기", group: "channel" },
  { key: "gamer-headset", label: "게이밍 헤드셋", group: "channel" },
  { key: "music-earbuds", label: "이어폰", group: "channel" },
  { key: "attend-stamp", label: "개근 도장", group: "attend" },
  { key: "month-trophy", label: "트로피", group: "attend" },
  { key: "hundred-cake", label: "백일 케이크", group: "attend" },
  { key: "veteran-mic", label: "빈티지 마이크", group: "attend" },
  { key: "allnight-headset", label: "철야 헤드셋", group: "attend" },
  { key: "morning-hello", label: "굿모닝", group: "attend" },
  { key: "growth-serum", label: "성장 물약", group: "attend" },
  { key: "allround-set", label: "가방", group: "bundle" },
  { key: "starter-pack", label: "선물 상자", group: "bundle" },
  { key: "night-set", label: "달 꾸러미", group: "bundle" },
  { key: "forge-coupon", label: "강화 할인권", group: "effect" },
  { key: "cashback-coin", label: "캐시백 동전", group: "effect" },
  { key: "binok-pickaxe", label: "빙옥 곡괭이", group: "effect" },
  { key: "promo-badge", label: "승급 배지", group: "effect" },
  { key: "quest-scroll", label: "두루마리", group: "effect" },
  { key: "pass-rocket", label: "로켓", group: "effect" },
  { key: "cooldown-hourglass", label: "모래시계", group: "effect" },
  { key: "soundproof-booth", label: "방음 부스", group: "effect" },
  { key: "streak-shield", label: "불꽃 방패", group: "effect" },
  { key: "jackpot-slot", label: "슬롯머신", group: "effect" },
  { key: "lucky-clover", label: "네잎클로버", group: "effect" },
  { key: "party-together", label: "함께", group: "effect" },
  { key: "welcome-fairy", label: "요정", group: "effect" },
  { key: "card-skin", label: "반짝 카드", group: "effect" },
  { key: "profile-badge", label: "리본 배지", group: "effect" },
  { key: "xp-bolt", label: "번개", group: "effect" },
];

const ART_KEYS = new Set(ITEM_ARTS.map((a) => a.key));
export const isArtKey = (k) => ART_KEYS.has(String(k || ""));
// "art:xp-potion" → "xp-potion", 일러스트가 아니면 ""
export const artKeyOf = (icon) => {
  const s = String(icon ?? "");
  if (!s.startsWith(ART_PREFIX)) return "";
  const k = s.slice(ART_PREFIX.length);
  return ART_KEYS.has(k) ? k : "";
};

// ───────────────────────── 공용 팔레트 ─────────────────────────
// 계열마다 0 외곽 · 1 어두움(빛 쪽 외곽) · 2 보통 · 3 밝음 · 4 빛. 단계가 오를수록 색조가 따뜻한 쪽으로 돈다.
//    새 아이콘도 이 안에서만 고른다(세트가 한 벌로 보이게).
export const ART_PALETTE = {
  // 빨강 (2 = 사이트 강조에 가깝게)
  r0: "#3b0d2c", r1: "#931a45", r2: "#e2263f", r3: "#ff6a4f", r4: "#ffbf94",
  // 주황
  o0: "#4a1428", o1: "#b33a1c", o2: "#f2731f", o3: "#ffae3c", o4: "#ffe48c",
  // 노랑 · 금
  y0: "#4c1f1c", y1: "#c0651a", y2: "#fbbd2a", y3: "#ffdd45", y4: "#fff7b0",
  // 초록
  g0: "#11303f", g1: "#18684f", g2: "#2ea447", g3: "#86d44a", g4: "#dcf48e",
  // 청록
  t0: "#102746", t1: "#11677b", t2: "#18aa99", t3: "#5ce0b2", t4: "#cbfad6",
  // 하늘
  s0: "#171f4f", s1: "#1e54a6", s2: "#2896de", s3: "#7ad4f5", s4: "#d9fbff",
  // 파랑
  b0: "#1b1447", b1: "#2e2f9f", b2: "#3f66e2", b3: "#76aaff", b4: "#c6e3ff",
  // 보라
  p0: "#2a1044", p1: "#5b2698", p2: "#9447d8", p3: "#cf82f0", p4: "#f7cbf3",
  // 분홍
  k0: "#460f34", k1: "#a42263", k2: "#ea508f", k3: "#ff92ad", k4: "#ffd8d0",
  // 갈색 · 나무
  n0: "#2d1323", n1: "#66301f", n2: "#a3592a", n3: "#d89346", n4: "#f4cc7b",
  // 크림 · 종이 (외곽은 갈색 n0 · n1)
  c1: "#c98d57", c2: "#eec389", c3: "#fbe7b8", c4: "#fffaea",
  // 쇠 · 회색
  a0: "#1c1a31", a1: "#464a6e", a2: "#7e88a8", a3: "#bec7d9", a4: "#eef2f6",
  w: "#ffffff",
};

// ───────────────────────── 그림 ─────────────────────────
// pal 의 값은 ART_PALETTE 이름. 지도는 위에서 아래로 16줄, 줄마다 16칸.

const SPRITES = {
  // ── 아이템 ──
  "xp-potion": {
    pal: { o: "g0", l: "g1", m: "g2", L: "g3", h: "g4", w: "w", G: "s4", C: "n3", c: "n2", R: "r2" },
    map: [
      "......oooo......",
      ".....oCCCco.....",
      "....llCcccoo....",
      "....lGwGGGGo....",
      ".....lRRRRo.....",
      ".....lwGGGo.....",
      "...llGwGGGGoo...",
      "..lLwhhLLLLLmo..",
      ".lLwLLmmmmmmmlo.",
      ".lLwLmmmmmmmllo.",
      ".lLLmmmmmhmmllo.",
      ".lLmmmmmmmmmllo.",
      ".oLmmmmmmmmlwlo.",
      "..olmhmmmmlllo..",
      "...oolGGGGloo...",
      ".....oooooo.....",
    ],
  },
  "attend-potion": {
    pal: { o: "b0", l: "b1", m: "b2", L: "b3", G: "b4", w: "w", C: "n3", c: "n2", R: "r2", P: "c3" },
    map: [
      "......oooo......",
      ".....oCCCco.....",
      "....llCcccoo....",
      "....lGwGGGGo....",
      ".....lRRRRo.....",
      ".....lwGGGo.....",
      "...lllwGGGooo...",
      "..lwLLLLLLLLLo..",
      "..lwLmmmmmmmlo..",
      "..lwmPPPPRPmlo..",
      "..lwmPRPRPPmlo..",
      "..lmmPPRPPPmlo..",
      "..ommPPPPPPmlo..",
      "..ommmmmmmmwlo..",
      "..olGGGGGGGGlo..",
      "...oooooooooo...",
    ],
  },
  "music-ticket": {
    pal: { o: "k0", l: "k1", m: "k2", L: "k3", h: "k4", w: "w" },
    map: [
      "................",
      "................",
      "................",
      ".lllllllllllllo.",
      "lhLLLLLLLLLlLLLo",
      "lLmmmmmwwmmmmmmo",
      "lLmmmmmwmwmlmmmo",
      ".lmmmmmwmmmmmmo.",
      ".lmmmwwwmmmlmmo.",
      "lLmmmwwwmmmmmmmo",
      "lLmmmmmmmmmlmmmo",
      "ollllllllllllllo",
      ".oooooooooooooo.",
      "................",
      "................",
      "................",
    ],
  },
  "slowmode-off": {
    pal: { o: "o0", l: "o1", d: "o1", m: "o2", L: "o3", w: "w", R: "r2", n: "n1", N: "n0", g: "c2", c: "c1" },
    map: [
      "...........RRR..",
      "..........RwwwR.",
      ".........RwRwwwR",
      ".........RwwRwwR",
      ".........RwwwRwR",
      "...lllo...RwwwR.",
      "..lwLLmo...RRR..",
      ".lLmdddmo..N.N..",
      ".lLdmLmdo..n.n..",
      ".lmdmdmdo..nnn..",
      ".omdmmdmo.ngggN.",
      "..odddmonnggggN.",
      ".ngooooggggggcN.",
      "ngggggggggccccN.",
      ".NNNNNNNNNNNNN..",
      "................",
    ],
  },

  // ── 시간대 ──
  "owl-charm": {
    pal: { o: "p0", l: "p1", d: "p1", m: "p2", L: "p3", h: "p4", Y: "y3", K: "a0", w: "w", B: "o2" },
    map: [
      "................",
      "..l..........o..",
      "..lLo......lmo..",
      "..lLmllllllmdo..",
      "..lLmmmmmmmmdo..",
      ".lLmYYmmmmYYmdo.",
      ".lLYwKYmmYwKYdo.",
      ".lmYKKYmmYKKYdo.",
      ".lmmYYmBBmYYmdo.",
      ".ommmmmBBmmmmdo.",
      ".ommmLLLLLLmmdo.",
      ".ommLhmLLmLLmdo.",
      ".ommLLLLLLLLmdo.",
      "..omLLmLLmLLmo..",
      "...odmLLLLmdo...",
      "....oBBooBBo....",
    ],
  },
  "early-bird": {
    pal: { o: "s0", l: "s1", d: "s1", m: "s2", L: "s3", W: "s4", B: "o2", S: "y1", Y: "y3", h: "y4" },
    map: [
      ".SSS............",
      "ShYYS...........",
      "SYYYS...........",
      "SYYYS...........",
      ".SSS............",
      ".....lllllo.....",
      "....lLLLmmmo....",
      "...lLLmmmmmmo...",
      "...lLmmmmmomo...",
      ".lllmmdddmomoBB.",
      "ldddmddddmmmoB..",
      ".ooommddWWmmo...",
      "...ommmWWWWdo...",
      "....odmWWddo....",
      ".....oooooo.....",
      "......B..B......",
    ],
  },
  "lunch-box": {
    pal: { o: "s0", l: "s1", d: "s1", m: "s2", L: "s3", w: "w", R: "r2", G: "g2", F: "g3", Y: "y3", y: "y2" },
    map: [
      "................",
      "................",
      ".lllllllllllllo.",
      "lddddddddddddddo",
      "ldwwwwwwdGFFGGdo",
      "ldwwRRwwdFGGFGdo",
      "ldwwRRwwdGGFGGdo",
      "ldwwwwwwdYYYYYdo",
      "ldwwwwwwdyyyyydo",
      "lLLLLLLLLLLLLLmo",
      "lwwmmmmmmmmmmmdo",
      "ommmmmmmmmmmmmdo",
      "oddddddddddddddo",
      ".oooooooooooooo.",
      "................",
      "................",
    ],
  },
  radio: {
    pal: { o: "t0", l: "t1", D: "t1", m: "t2", L: "t3", h: "t4", c: "c3", r: "r2", a: "a2" },
    map: [
      "..............r.",
      "..............a.",
      ".............a..",
      "....lllll....a..",
      "...l.....o..a...",
      "...l.....o..a...",
      ".lllllllllllllo.",
      "lhLLLLLLLLLLLLmo",
      "lhLDDDDLLccrccmo",
      "lhDoDoDDLccrccmo",
      "lhDDoDoDLccrccmo",
      "ohDoDoDDLLLLLLmo",
      "ohDDoDoDLccLccmo",
      "ohLDDDDLLLLLLLmo",
      "ommmmmmmmmmmmmmo",
      ".oooooooooooooo.",
    ],
  },
  "night-lantern": {
    pal: { o: "b0", l: "b1", D: "b1", M: "b2", L: "b3", Y: "y2", y: "y3", F: "o2", f: "o3", w: "w" },
    map: [
      ".......lo.......",
      "......l..o......",
      ".....lllllo.....",
      "....lLMMMMDo....",
      "...lllllllllo...",
      "...lMYyyyyYDo...",
      "...lMwyyFyYDo...",
      "...lMwyFFyYDo...",
      "...lMyFFfFYDo...",
      "...lMyFfwFYDo...",
      "...lMyFfwFYDo...",
      "...lMYyFFyYDo...",
      "...oooooooooo...",
      "....oLMMMMDo....",
      ".....oooooo.....",
      "................",
    ],
  },

  // ── 요일 ──
  "weekend-sword": {
    pal: { o: "r0", l: "r1", d: "r1", m: "r2", L: "r3", w: "w", Y: "y3", y: "y2", k: "a0", S: "a4", A: "a2" },
    map: [
      "...........kk...",
      "..........kwAk..",
      "..........kSAk..",
      ".lllllllllkSAk..",
      ".lwLLLLLLLkSAk..",
      ".lLmmmmmmdkSAk..",
      ".lLmmYmmmdkSAk..",
      ".lLmYYymmdkSAk..",
      ".lLmmymmmdkSAk..",
      ".lLmmmmmkkkSAkkk",
      ".oLmmmmmkYYYyyyk",
      "..oLmmmmkkkddkkk",
      "...oLmmdo.kmdk..",
      "....omdo..kmdk..",
      ".....oo...kYyk..",
      "...........kk...",
    ],
  },
  "friday-fire": {
    pal: { o: "r0", d: "r1", R: "r2", O: "o2", Y: "y3", W: "y4", w: "w" },
    map: [
      "......o.........",
      ".....oRo........",
      ".....oRRo...o...",
      "....oRRRo..oRo..",
      "....oRRRRooRRo..",
      "...oRRORRRoRRo..",
      "...oRROORRRRRRo.",
      "..oRROOOORRRRRo.",
      "..oRROOYOOORRdo.",
      ".oRROOYYYOOORdo.",
      ".oRROOYYYYOORdo.",
      ".oRROYYWWYYORdo.",
      ".oRROYYWwYYORdo.",
      "..oRROYYYYORdo..",
      "...oRROOOORdo...",
      "....oooooooo....",
    ],
  },
  "monday-vaccine": {
    pal: { o: "t0", w: "w", L: "t3", h: "t4", d: "t2", G: "s4", N: "a2", P: "a3", D: "a1" },
    map: [
      "...............N",
      "..............N.",
      "..........o..N..",
      ".........owNN...",
      "........owLLN...",
      ".......owLhLdo..",
      "......owLLLdo...",
      "....oowGLLdo....",
      "...oPwGGGdo.....",
      "...oPPGGDo......",
      "....oPPDo.......",
      ".oooPoPPo.......",
      "oPPPo.oo........",
      ".oPPo...........",
      "..oPo...........",
      "...o............",
    ],
  },
  "wednesday-coffee": {
    pal: { o: "n0", l: "n1", n: "n1", N: "n2", M: "n3", h: "c4", L: "c3", m: "c2", d: "c1", a: "a3" },
    map: [
      "................",
      ".....a....a.....",
      "....aa...aa.....",
      "....a....a......",
      "....aa...aa.....",
      "..lllllllllo....",
      ".lhLLLLLLLLLo...",
      ".lLNMNNNNNNmooo.",
      ".lLnnnnnnnnmoLmo",
      ".lhLLLLLLLLmoomo",
      ".lLmmmmmmmmdoomo",
      ".oLmmmmmmmmdommo",
      ".oLmmmmmmmmdooo.",
      "..odmmmmmmdo....",
      "...oooooooo.....",
      "................",
    ],
  },

  // ── 채널 ──
  "scrim-mic": {
    pal: { o: "y0", l: "y1", d: "y1", m: "y2", L: "y3", h: "y4", w: "w", k: "a0", D: "a1", a: "a2", A: "a3" },
    map: [
      ".....lllllo.....",
      "....lhLLLLmo....",
      "...lLwLmLmLmo...",
      "...lLLmLmLmdo...",
      "...lLmLmLmmdo...",
      "...omLmLmdmdo...",
      "....omdmdmdo....",
      "....kAAAAaak....",
      ".....kAaaDk.....",
      ".....kAaaDk.....",
      ".....kAaaDk.....",
      ".....kAaaDk.....",
      ".....kAaaDk.....",
      "......kAak......",
      "......kAak......",
      "......kkkk......",
    ],
  },
  "chat-megaphone": {
    pal: { o: "o0", l: "o1", d: "o1", D: "o1", m: "o2", L: "o3", h: "o4", w: "w", g: "a3", G: "a2" },
    map: [
      "................",
      "...........lo...",
      ".........llLLo..",
      "........lmmLDo..",
      "......llLhmLDo..",
      ".lllllLhmmmLDo..",
      "lgggwLmmmmmLDo..",
      "lgggmmmmmmmLDo..",
      "oGGGmmmmmmmLDo..",
      "oGGGdddddddLDo..",
      ".oooGGdddddLDo..",
      "...oGGoodddLDo..",
      "...oGGo.oddLDo..",
      "....oo...ooDDo..",
      "...........oo...",
      "................",
    ],
  },
  "gamer-headset": {
    pal: { o: "a0", l: "a1", D: "a1", m: "a2", B: "a2", L: "a3", W: "a4", e: "g4", g: "g3", G: "g2" },
    map: [
      "................",
      ".....lllllo.....",
      "...llmmmmmmoo...",
      "..lmWLLLLLLLmo..",
      ".lmmmmoooommmmo.",
      ".lmmoo....oommo.",
      ".lmmo......ommo.",
      "lmDDDo....oDDDDo",
      "lmeDDo....oDDeDo",
      "lmgDDo....oDDgDo",
      "lmgDDo....oDDgDo",
      "lmGDDo....oDDGDo",
      "omGDDo....oDDGDo",
      ".oDDBoooo..oDDo.",
      "..oooBBBGo..oo..",
      ".....oooo.......",
    ],
  },
  "music-earbuds": {
    pal: { o: "a0", l: "a1", K: "a1", d: "a3", W: "a4", w: "w", P: "k2", p: "k1", Q: "k3" },
    map: [
      "........PPP.....",
      "........P.P.....",
      "........P.......",
      "......QPP.......",
      "......Pp........",
      "..lll......lll..",
      ".lwwWo....lwwWo.",
      "lwwwWWo..lwwwWWo",
      "lwwWKdo..lwKwWdo",
      "lwWWKdo..lWKWWdo",
      ".lWddo....lWddo.",
      ".lWdo......lWdo.",
      ".lWdo......lWdo.",
      ".lWdo......lWdo.",
      ".oddo......oddo.",
      "..oo........oo..",
    ],
  },

  // ── 출석 ──
  "attend-stamp": {
    pal: { o: "n0", d: "n1", l: "n1", m: "n2", L: "n3", h: "n4", R: "r2", r: "r1" },
    map: [
      "..lllo..........",
      ".lLhmmo.........",
      ".lLmmdo.........",
      "..lLdo..........",
      "..lmdo..........",
      "..lmdo..........",
      "lllllllo........",
      "lhLLLLdo........",
      "lmmmmmdo........",
      "ommmmmdo...RRR..",
      "oRRRRRro..R...R.",
      ".oooooo..R....RR",
      ".........R.R.R.R",
      ".........R..R..R",
      "..........R...R.",
      "...........RRR..",
    ],
  },
  "month-trophy": {
    pal: { o: "y0", l: "y1", d: "y1", m: "y2", L: "y3", h: "y4", w: "w", M: "n3", N: "n2", n: "n1" },
    map: [
      "....lllllllo....",
      "..llhLLLmmmdoo..",
      ".lmoLwmmmmddodo.",
      "lmooLwmmmmddoodo",
      "lmooLmmmmmddoodo",
      ".omooLmmmddoodo.",
      "..o..ommddo..o..",
      "......omdo......",
      ".....oomdoo.....",
      "....lLmmmddo....",
      "...lMMMMMMNNo...",
      "...lNNLLLLnno...",
      "...oNNNNNNnno...",
      "...onnnnnnnno...",
      "....oooooooo....",
      "................",
    ],
  },
  "hundred-cake": {
    pal: { o: "n0", l: "n1", K: "k3", k: "k2", w: "w", C: "c3", c: "c1", Y: "y3", F: "o2", B: "s2" },
    map: [
      "................",
      "...Y...Y...Y....",
      "...F...F...F....",
      "...B...B...B....",
      "...w...w...w....",
      "...B...B...B....",
      ".llllllllllllo..",
      "lKKKKKKKKKKKKKo.",
      "lKwKKKKKKKKKKko.",
      "lkkCkkCkCkkCkko.",
      "lkCCkCCkCCkCCko.",
      "lCCCCCCCCCCCCco.",
      "okkkkkkkkkkkkko.",
      "oCCCCCCCCCCCCco.",
      "occccccccccccco.",
      ".ooooooooooooo..",
    ],
  },
  "veteran-mic": {
    pal: { o: "a0", l: "a1", D: "a1", d: "a1", m: "a2", L: "a3", w: "w", Y: "y3", y: "y2", h: "y4" },
    map: [
      "......lllo......",
      ".....lLmmmo.....",
      "....lLwmDmdo....",
      "....lLDmDmdo....",
      "...llLmDmDdoo...",
      "..lYohYYYyyoyo..",
      "..lYoLDmDmdoyo..",
      "..lYoLmDmDdoyo..",
      "..oYoLDmDmdoyo..",
      "...oYommddoyo...",
      "....oYooooyo....",
      ".....ooYyoo.....",
      ".....ooYyoo.....",
      "....lLmmmmdo....",
      "...oDDDDDDDDo...",
      "....oooooooo....",
    ],
  },
  "allnight-headset": {
    pal: { o: "p0", l: "p1", d: "p1", m: "p2", L: "p3", h: "p4", C: "k3", K: "k2", Y: "y3" },
    map: [
      "................",
      "................",
      ".....lllllo.....",
      "...llhLLLLmoo...",
      "..lLLLmmmmmmdo..",
      ".lLmmoooooommdo.",
      ".lLmo......omdo.",
      ".lLmo......omdo.",
      "lllllo....oooooo",
      "lLmmCo.YY.oCmmdo",
      "lLmmCoYY..oCmmdo",
      "lLmmCoYY..oCmmdo",
      "oLmmKoYY..oKmmdo",
      "odddKo.YY.oKdddo",
      ".ooooo....ooooo.",
      "................",
    ],
  },
  "morning-hello": {
    pal: { o: "o0", l: "o1", d: "o1", m: "o2", L: "o3", w: "w", K: "k3", Y: "y3", W: "y4" },
    map: [
      ".......WY.......",
      ".WY....YY....WY.",
      ".YY..........YY.",
      "......llll......",
      "....llLLLLoo....",
      "...lLwLmmmmmo...",
      "...lLmommomdo...",
      "WY.lLmommomdo.WY",
      "YY.lKKmmmmKKo.YY",
      "...ommommomdo...",
      "...odmmoomddo...",
      "....ooddddoo....",
      "......oooo......",
      ".WY..........WY.",
      ".YY....WY....YY.",
      ".......YY.......",
    ],
  },
  "growth-serum": {
    pal: { o: "t0", l: "t1", d: "t1", m: "t2", L: "t3", h: "t4", w: "w", G: "s4", F: "g3", g: "g2", R: "r2" },
    map: [
      ".ooo.......ooo..",
      "oFFFoo...ooFFgo.",
      "oFFggdodoFgggdo.",
      ".ogggddddgggdo..",
      "..ooooodooooo...",
      ".......d........",
      "....llldoooo....",
      "....lGwdGGGo....",
      ".....lRRRRo.....",
      ".....lwhhLo.....",
      ".....lwLmlo.....",
      ".....lwmhlo.....",
      ".....lLmmwo.....",
      ".....lmhmlo.....",
      ".....olGGlo.....",
      "......oooo......",
    ],
  },

  // ── 묶음 ──
  "allround-set": {
    pal: { o: "n0", l: "n1", d: "n1", B: "n1", N: "n2", M: "n3", h: "n4", Y: "y3", y: "y2", T: "y1" },
    map: [
      "......lllo......",
      ".....lMNNNo.....",
      "....lNooooNo....",
      "...lhMMMMMNdo...",
      "..lMMNNNNNNNdo..",
      ".lMNNNNNNNNNNdo.",
      ".lMNNNNNNNNNNdo.",
      ".lNNNNNYyNNNNdo.",
      ".odddddyTdddddo.",
      ".oBBBBBBBBBBBBo.",
      ".oBBMMMMMMMMBBo.",
      ".oBBNNNNNNNNBBo.",
      ".oBBNNNNNNNNBBo.",
      ".oBBNNNNNNNNBBo.",
      "..oBBBBBBBBBBo..",
      "...oooooooooo...",
    ],
  },
  "starter-pack": {
    pal: { o: "b0", l: "b1", D: "b1", M: "b2", L: "b3", h: "b4", q: "y0", r: "y1", R: "y2", Y: "y3", H: "y4" },
    map: [
      "...qqq....qqq...",
      "..qHYRq..qYRrq..",
      ".qYRRRRqqYRRRrq.",
      "..qrRRRRRRRRrq..",
      ".llqqqqYRqqqqoo.",
      "lhLLLLLYRLLLLLLo",
      "lLMMMMMRrMMMMMDo",
      "oDDDDDDRrDDDDDDo",
      ".lLMMMMRrMMMMDo.",
      ".lLMMMMRrMMMMDo.",
      ".lLMMMMRrMMMMDo.",
      ".oLMMMMRrMMMMDo.",
      ".oLMMMMRrMMMMDo.",
      ".oDDDDDRrDDDDDo.",
      "..oooooooooooo..",
      "................",
    ],
  },
  "night-set": {
    pal: { o: "p0", l: "p1", d: "p1", P: "p2", L: "p3", h: "p4", T: "y1", y: "y2", Y: "y3", W: "y4" },
    map: [
      ".....lllllo.....",
      "....lLPPPPdo....",
      "...lLPPPPPPdo...",
      "....oYYYYYYyT...",
      "...lLPPPPPPdT...",
      "..lLhPPPPPPPdo..",
      ".lLLPPPPPPPPPdo.",
      "lLPPPPPYYPPPPPdo",
      "lLPPPPWYPPPWPPdo",
      "lPPPPPWYPPPPPPdo",
      "lPPPPPYYPPPPPPdo",
      "oPPPPPPYYPPYPPdo",
      ".oPPPPPPPPPPPdo.",
      "..oddddddddddo..",
      "...oooooooooo...",
      "................",
    ],
  },

  // ── 효과 ──
  "forge-coupon": {
    pal: { q: "t0", k: "t1", D: "t1", R: "t2", T: "t3", w: "w", o: "a0", d: "a1", l: "a1", m: "a2", L: "a3" },
    map: [
      "..kkkkkkkkkkkq..",
      ".kwTTTTTTTTTTRq.",
      ".kRRRRwRRwRRRRq.",
      "..kRRRRRwRRRRq..",
      "..kRRRRwRRRRRq..",
      ".kRRRRwRRwRRRRq.",
      ".qDDDDDDDDDDDDq.",
      "..qqqqqqqqqqqq..",
      ".llwLLLLLLLLLLo.",
      "lmmmmmmmmmmmmdo.",
      ".ooommmmmmmdoo..",
      "....oommmdoo....",
      "....oommmdoo....",
      "...lLmmmmmmdo...",
      "..oddddddddddo..",
      "...oooooooooo...",
    ],
  },
  "cashback-coin": {
    pal: { o: "y0", l: "y1", d: "y1", m: "y2", L: "y3", h: "y4", w: "w", G: "g2", H: "g3" },
    map: [
      "................",
      ".....lllllo.....",
      "...llhLLLmmoo...",
      "..lLLmmmGmmmdo..",
      "..lLwmHGGGmmdo..",
      ".lLLmHGGGGmmmdo.",
      ".lLmGGmmGmmmmdo.",
      ".lLmGGmmmmGGddo.",
      ".lLmGGmmmmGGddo.",
      ".oLmGGmmmmGGddo.",
      ".ommmGGGGGGmddo.",
      "..ommmGGGGmddo..",
      "..odmmmmmmdddo..",
      "...ooddddddoo...",
      ".....oooooo.....",
      "................",
    ],
  },
  "binok-pickaxe": {
    pal: { o: "a0", d: "a1", l: "a1", m: "a2", L: "a3", w: "w", H: "n2", q: "s0", D: "s1", S: "s2", s: "s3" },
    map: [
      "....lll.........",
      "...lwLLoo.......",
      "..lLooLLmo......",
      "...o..ooLmo.....",
      "........oLmo....",
      ".........oLmo...",
      "........oHoLmo..",
      ".......oHo.omo..",
      "......oHo..odo..",
      ".....oHo..DDq...",
      "....oHo..Dwssq..",
      "...oHo..DwsSSSq.",
      "..oHo...qsSSSDq.",
      ".oHo.....qSSDq..",
      "..o.......qDq...",
      "...........q....",
    ],
  },
  "promo-badge": {
    pal: { o: "y0", l: "y1", D: "y1", T: "y2", Y: "y3", h: "y4", d: "g1", m: "g2", L: "g3", w: "w" },
    map: [
      ".......lo.......",
      ".....llhYoo.....",
      "...llYYLLTToo...",
      "..lYYLLmmmmTTo..",
      ".lYLLmmwwmmmmTo.",
      ".lYLmmwwwwmmmTo.",
      ".lYLmwwwwwwmdTo.",
      ".lYLmmmwwdddmTo.",
      ".lYLmmmwwdmmmTo.",
      ".oYmmmmwwdmmdTo.",
      ".oYmmmmwwdmmdDo.",
      ".oTmmmmmddmddDo.",
      "..oTmmmmmmddDo..",
      "...ooTmmddDoo...",
      ".....ooTDoo.....",
      ".......oo.......",
    ],
  },
  "quest-scroll": {
    pal: { o: "n0", l: "n1", n: "n1", N: "n2", c: "c1", C: "c2", L: "c3", h: "c4", R: "r2" },
    map: [
      "..lllllllllllo..",
      ".lhLLLLLLLLLLLo.",
      "lNCCCCCCCCCCCcNo",
      ".occcccccccccco.",
      "..oooooooooooo..",
      "..ohRLRLnnnLCo..",
      "..ohLRLLLLLLCo..",
      "..ohRLRLnnLLCo..",
      "..ohLLLLLLLLCo..",
      "..ohnnnLnnnnCo..",
      "..ohLLLLLLLLCo..",
      "..oooooooooooo..",
      ".lhLLLLLLLLLLLo.",
      "lNCCCCCCCCCCCcNo",
      ".occcccccccccco.",
      "..oooooooooooo..",
    ],
  },
  "pass-rocket": {
    pal: { o: "a0", A: "a2", M: "a3", w: "w", K: "r1", d: "r1", R: "r2", L: "r3", B: "s2", F: "o2", Y: "y3" },
    map: [
      ".......Ko.......",
      "......KLRo......",
      ".....KLRRdo.....",
      "....KLRRRRdo....",
      "....AwwwwwMo....",
      "....AwwoowMo....",
      "....AwowBoMo....",
      "....AwoBBoMo....",
      "....AwwoowMo....",
      "...KAwwwwwMoo...",
      "..KRowwwwMModo..",
      ".KLRowwwMMAoddo.",
      ".ooooAAAAAAoooo.",
      "....oooooooo....",
      "......FYYF......",
      ".......FF.......",
    ],
  },
  "cooldown-hourglass": {
    pal: { o: "n0", l: "n1", d: "n1", N: "n2", L: "n3", h: "n4", w: "w", Y: "y3", y: "y2", G: "s4" },
    map: [
      "..lllllllllllo..",
      ".lhLLLLLLLLLLNo.",
      ".lNNNNNNNNNNNdo.",
      "..oooooooooooo..",
      "...owYYYYYYGo...",
      "....oYYYYYyo....",
      ".....oYYYyo.....",
      "......oYyo......",
      "......oYyo......",
      ".....oGYyGo.....",
      "....oGwYyGGo....",
      "...oYYYYYyyyo...",
      "..oooooooooooo..",
      ".lhLLLLLLLLLLNo.",
      ".oNNNNNNNNNNNdo.",
      "..oooooooooooo..",
    ],
  },
  "soundproof-booth": {
    pal: { o: "g0", l: "g1", d: "g1", m: "g2", L: "g3", h: "g4", S: "s3", s: "s2", w: "w", k: "a0", R: "r2" },
    map: [
      "...oRo..........",
      "llllllllo.......",
      "lhLLLLLmo.......",
      "lLmmmmmdo.......",
      "lLooooodo.......",
      "lLowSSodo.......",
      "lLoSSsodo.......",
      "lLoSssodo.......",
      "lLommmodok......",
      "lLommmodkwk.R..R",
      "oLommokkwwk..RR.",
      "oLommmkwwwk..RR.",
      "oLommmkkwwk.R..R",
      "oLommmodkwk.....",
      "oooooooook......",
      "................",
    ],
  },
  "streak-shield": {
    pal: { o: "b0", l: "b1", d: "b1", m: "b2", L: "b3", h: "b4", w: "w", R: "r2", O: "o2", Y: "y3", W: "y4" },
    map: [
      "..lllllllllllo..",
      ".lhLLLLLLLLmddo.",
      ".lLwmmmmmmmdddo.",
      ".lLmmmmRmmmdddo.",
      ".lLmmmmRRmmdddo.",
      ".lLmmmRRRmRdddo.",
      ".lLmmmRORRRdddo.",
      ".lLmmRROORRdddo.",
      ".lLmmROOYORRddo.",
      "..lLmROYWYORdo..",
      "..oLmROYWYORdo..",
      "...oLmROOORdo...",
      "....ommmmddo....",
      ".....ommddo.....",
      "......oddo......",
      ".......oo.......",
    ],
  },
  "jackpot-slot": {
    pal: { o: "r0", l: "r1", d: "r1", m: "r2", R: "r2", L: "r3", w: "w", W: "a4", a: "a2", Y: "y3", y: "y2", h: "y4" },
    map: [
      "................",
      "....lllllo......",
      ".lllhYYYYyoo.Lm.",
      "lLLLLLLLLLLdomd.",
      "lLmmmmmmmmmdo.a.",
      "lLmWWWWWWWmdo.a.",
      "lLmwRRRRRwmdo.a.",
      "lLmwwwwRwwmdo.a.",
      "lLmwwwRwwwmdoaa.",
      "lLmwwRwwwwmdo...",
      "lLmWWRWWWWmdo...",
      "oLmmmmmmmmmdo...",
      "oLmdddddddmdo...",
      "oLmmmmmmmmmdo...",
      ".oddddddddddo...",
      "..oooooooooo....",
    ],
  },
  "lucky-clover": {
    pal: { o: "g0", l: "g1", m: "g2", L: "g3", h: "g4", w: "w", Y: "y3" },
    map: [
      "....lll.llo...Y.",
      "...lLLLoLLmo.YwY",
      "...lLLmhmmlo..Y.",
      ".ll.lLmhmll.ll..",
      "lLLl.lmmll.lLmo.",
      "lLLml.lll.lLLmo.",
      "lLmmml.l.lLLmmo.",
      ".ohhmlllllmhho..",
      "lLmmll.lmlmmmlo.",
      "lLmll.lllmlmllo.",
      "omll.lLmmlmlllo.",
      ".oo.lLLhmllmoo..",
      "...lLLmhmmlomo..",
      "...lmmlomlloomo.",
      "....ooo.ooo..o..",
      "................",
    ],
  },
  "party-together": {
    pal: { a: "s0", S: "s2", T: "s3", q: "g0", G: "g2", H: "g3", o: "o0", l: "o1", d: "o1", O: "o2", L: "o3" },
    map: [
      "................",
      ".aaa........qqq.",
      "aTSSa.lllo.qHGGq",
      "aSSSalLLOOoqGGGq",
      "aSSSalLOOdoqGGGq",
      ".aaa.oOOOdo.qqq.",
      "......oooo......",
      ".aaaalllllqqqqq.",
      "aTSSoLOOOOdoHGGq",
      "aTSoLOOOOOOdoGGq",
      "aSSoLOOOOOOdoGGq",
      "aSSoLOOOOOOdoGGq",
      "aSSoLOOOOOOdoGGq",
      ".aaoOOOOOOOdoqq.",
      "...oooooooooo...",
      "................",
    ],
  },
  "welcome-fairy": {
    pal: { o: "y0", l: "y1", d: "y1", T: "y2", Y: "y3", h: "y4", w: "w", n: "k0", P: "k2", Q: "k3" },
    map: [
      "..........l.....",
      ".........lho....",
      "..Y......lYo....",
      ".YwY..lllYYYooo.",
      "..Y...lhYYYYTdo.",
      ".......lYYYTdo..",
      "........oYTdo...",
      ".......oYdoTdo..",
      ".......oonn.oo..",
      "........nQn.....",
      ".......nPn......",
      "......nQn.......",
      ".....nPn........",
      "....nQn.........",
      "...nPn..........",
      "....n...........",
    ],
  },
  "card-skin": {
    pal: { o: "p0", B: "p1", Y: "y3", y: "y2", d: "y1", f: "p1", s: "s3", k: "k3", r: "r2", w: "w" },
    map: [
      ".....ooooooooo..",
      "....oBByBByBBBo.",
      "...oooooooooBBo.",
      "..fYYYYYYYYyoBo.",
      "..fYyfwskfydoyo.",
      "..fYfwskfffdoBo.",
      "..fYwskffffdoBo.",
      "..fYskfYfffdoyo.",
      "..fYkfYwyffdoBo.",
      "..fYfYkrrdfdoBo.",
      "..fYfyrrrdfdoyo.",
      "..fYffyrdfsdoBo.",
      "..fYfffdfskdoBo.",
      "..fYyfffskydoo..",
      "..oyddddddddo...",
      "...ooooooooo....",
    ],
  },
  "profile-badge": {
    pal: { o: "k0", l: "k1", d: "k1", m: "k2", L: "k3", h: "k4", w: "w", y: "y2", Y: "y3", H: "y4", T: "y1" },
    map: [
      ".......lo.......",
      "......lhLo......",
      "....lllLLooo....",
      "...lhLLLmmmmo...",
      "...lLLLYYmmmo...",
      "..llLLYYYYmmoo..",
      ".lLLLYHwYYymddo.",
      ".lLLmYYYYyydddo.",
      "..oommYYyTddoo..",
      "...ommmyTdddo...",
      "...ommmmddddo...",
      "..omoooddooodo..",
      "..ommdoddommdo..",
      ".ommdo.oo.ommdo.",
      ".omodo....omodo.",
      "..o.o......o.o..",
    ],
  },
  "xp-bolt": {
    pal: { o: "y0", l: "y1", d: "y1", T: "y2", Y: "y3", h: "y4", w: "w" },
    map: [
      "........llllo...",
      ".......lhhYYdo..",
      "......lhYYYdo...",
      ".....lhYYYdo....",
      "....lhYYYdo.....",
      "...lhwYYdoooo...",
      "..lhYYYYYTTTdo..",
      "...ooohYYTTdo...",
      ".....lYYTTdo....",
      "....lYYTTdo.....",
      "...lYYTdoo......",
      "...lYTdo........",
      "..lYTdo.........",
      "..oTdo..........",
      "...oo...........",
      "................",
    ],
  },
};

// ───────────────────────── 내보내기 ─────────────────────────

// 한 줄에서 같은 색이 이어지는 칸을 묶고, 바로 윗줄과 모양이 같으면 세로로 늘린다 — key 마다 한 번만 만든다
const bodies = new Map();
function bodyOf(key) {
  if (bodies.has(key)) return bodies.get(key);
  const s = SPRITES[key];
  let out = "";
  if (s) {
    const open = new Map(); // "x,w,색" → 아직 닫지 않은 rect
    const done = [];
    s.map.forEach((row, y) => {
      const runs = [];
      for (let x = 0; x < row.length; ) {
        const c = row[x];
        let e = x + 1;
        while (e < row.length && row[e] === c) e++;
        if (c !== ".") runs.push([x, e - x, ART_PALETTE[s.pal[c]]]);
        x = e;
      }
      const seen = new Set();
      for (const [x, w, fill] of runs) {
        const id = `${x},${w},${fill}`;
        seen.add(id);
        const r = open.get(id);
        if (r && r.y + r.h === y) r.h++;
        else {
          if (r) done.push(r);
          open.set(id, { x, y, w, h: 1, fill });
        }
      }
      for (const [id, r] of open) {
        if (seen.has(id)) continue;
        done.push(r);
        open.delete(id);
      }
    });
    done.push(...open.values());
    done.sort((a, b) => a.y - b.y || a.x - b.x);
    out = done.map((r) => `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" fill="${r.fill}"/>`).join("");
  }
  bodies.set(key, out);
  return out;
}

// svg 안쪽(rect 들)만 — React 는 <svg viewBox="0 0 16 16"> 에 이걸 넣는다.
//    예전 호출의 둘째 인자(uid)는 그대로 받아도 되지만 쓰지 않는다(그라데이션이 없어 id 가 필요 없다)
export function itemArtBody(key) {
  if (!isArtKey(key)) return "";
  return bodyOf(key);
}

// 완성된 SVG 문자열 — 서버 · node 스크립트 · 이미지 만들기에서 쓴다. size 는 16 의 배수가 가장 또렷하다({ uid } 는 무시)
export function itemArtSvg(key, { size = 48 } = {}) {
  const body = itemArtBody(key);
  if (!body) return "";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="${size}" height="${size}" shape-rendering="crispEdges" aria-hidden="true">${body}</svg>`;
}
