// 📌 아이템 도트 아이콘 — 16×16 픽셀 한 벌. 클라이언트·서버·node 공용 순수 JS(React·DOM 의존 없음).
//    icon 값이 "art:<key>" 면 ItemIcon 이 이 그림을 그린다. 목록은 ITEM_ARTS 하나 — lib/items.js 검증도 이걸 본다.
//    그림 규칙(게임 인벤토리 아이템 결):
//    · 아이콘마다 16줄 × 16글자 지도 + 글자→색 표. "." 은 투명
//    · 빛은 왼쪽 위. 음영은 같은 계열 램프(1 어두움 · 2 보통 · 3 밝음 · 4 빛)로 — 어두울수록 푸른·보랏빛, 밝을수록 따뜻하게
//    · 외곽선은 순검정 대신 물체 색의 0단계, 빛 받는 위·왼쪽 테두리는 1단계(sel-out). 속 경계선은 줄여 덩어리로 읽히게
//    · 재질 반사광: 유리·쇠는 흰 점·흰 줄 1~2칸, 반대편에 작은 반사 하나
//    · 색은 아래 공용 팔레트(ART_PALETTE)에서만, 아이콘당 10색 이내 — 그라데이션·흐림·반투명 금지
//    · 가로로 이어지는 같은 색 칸은 <rect> 하나로 묶고 shape-rendering="crispEdges"
//    · 화면에는 정수 배율(16·32·48…)로만 그린다 — 크기 맞춤은 ItemIcon 이 한다

export const ART_PREFIX = "art:";
// 격자 한 변(칸 수)
export const ART_GRID = 16;

// 묶음 — 아이콘 고르기 화면이 이 순서로 나눠 보여 준다
export const ITEM_ART_GROUPS = [
  { g: "item", label: "아이템" },
  { g: "time", label: "시간대" },
  { g: "day", label: "요일" },
  { g: "channel", label: "채널" },
  { g: "attend", label: "출석" },
  { g: "bundle", label: "묶음" },
  { g: "effect", label: "효과" },
  { g: "season", label: "시즌" },
];

export const ITEM_ARTS = [
  { key: "xp-potion", label: "XP 물약", group: "item" },
  { key: "attend-potion", label: "출석 물약", group: "item" },
  { key: "music-ticket", label: "음악 티켓", group: "item" },
  { key: "slowmode-off", label: "슬로우 해제", group: "item" },
  { key: "owl-charm", label: "올빼미 부적", group: "time" },
  { key: "early-bird", label: "얼리버드", group: "time" },
  { key: "lunch-box", label: "도시락", group: "time" },
  { key: "radio", label: "라디오", group: "time" },
  { key: "night-lantern", label: "등불", group: "time" },
  { key: "weekend-sword", label: "검과 방패", group: "day" },
  { key: "friday-fire", label: "불꽃", group: "day" },
  { key: "monday-vaccine", label: "백신", group: "day" },
  { key: "wednesday-coffee", label: "커피", group: "day" },
  { key: "scrim-mic", label: "금빛 마이크", group: "channel" },
  { key: "chat-megaphone", label: "확성기", group: "channel" },
  { key: "gamer-headset", label: "게이밍 헤드셋", group: "channel" },
  { key: "music-earbuds", label: "이어폰", group: "channel" },
  { key: "attend-stamp", label: "개근 도장", group: "attend" },
  { key: "month-trophy", label: "트로피", group: "attend" },
  { key: "hundred-cake", label: "백일 케이크", group: "attend" },
  { key: "veteran-mic", label: "빈티지 마이크", group: "attend" },
  { key: "allnight-headset", label: "철야 헤드셋", group: "attend" },
  { key: "morning-hello", label: "굿모닝", group: "attend" },
  { key: "growth-serum", label: "성장 물약", group: "attend" },
  { key: "allround-set", label: "가방", group: "bundle" },
  { key: "starter-pack", label: "선물 상자", group: "bundle" },
  { key: "night-set", label: "달 꾸러미", group: "bundle" },
  { key: "forge-coupon", label: "강화 할인권", group: "effect" },
  { key: "cashback-coin", label: "캐시백 동전", group: "effect" },
  { key: "binok-pickaxe", label: "빙옥 곡괭이", group: "effect" },
  { key: "promo-badge", label: "승급 배지", group: "effect" },
  { key: "quest-scroll", label: "두루마리", group: "effect" },
  { key: "pass-rocket", label: "로켓", group: "effect" },
  { key: "cooldown-hourglass", label: "모래시계", group: "effect" },
  { key: "soundproof-booth", label: "방음 부스", group: "effect" },
  { key: "streak-shield", label: "불꽃 방패", group: "effect" },
  { key: "jackpot-slot", label: "슬롯머신", group: "effect" },
  { key: "lucky-clover", label: "네잎클로버", group: "effect" },
  { key: "party-together", label: "함께", group: "effect" },
  { key: "welcome-fairy", label: "요정", group: "effect" },
  { key: "card-skin", label: "반짝 카드", group: "effect" },
  { key: "profile-badge", label: "리본 배지", group: "effect" },
  { key: "xp-bolt", label: "번개", group: "effect" },
  // 시즌 2 「A New World」(2026-10) — 공중섬 배지 · 시즌 상점 특수 배지 · 패스 한정 아이템
  { key: "sky-island", label: "공중섬", group: "season" },
  { key: "compass", label: "나침반", group: "season" },
  { key: "airship", label: "비공정", group: "season" },
  { key: "portal", label: "차원문", group: "season" },
  { key: "pioneer-flag", label: "개척 깃발", group: "season" },
  { key: "sky-seed", label: "하늘섬 씨앗", group: "season" },
  { key: "cloud-candy", label: "구름 솜사탕", group: "season" },
  { key: "wind-pinwheel", label: "바람개비", group: "season" },
  { key: "star-shard", label: "별똥별 조각", group: "season" },
];

const ART_KEYS = new Set(ITEM_ARTS.map((a) => a.key));
export const isArtKey = (k) => ART_KEYS.has(String(k || ""));
// "art:xp-potion" → "xp-potion", 일러스트가 아니면 ""
export const artKeyOf = (icon) => {
  const s = String(icon ?? "");
  if (!s.startsWith(ART_PREFIX)) return "";
  const k = s.slice(ART_PREFIX.length);
  return ART_KEYS.has(k) ? k : "";
};

// ───────────────────────── 공용 팔레트 ─────────────────────────
// 계열마다 0 외곽 · 1 어두움(빛 쪽 외곽) · 2 보통 · 3 밝음 · 4 빛. 단계가 오를수록 색조가 따뜻한 쪽으로 돈다.
//    새 아이콘도 이 안에서만 고른다(세트가 한 벌로 보이게).
export const ART_PALETTE = {
  // 빨강 (2 = 사이트 강조에 가깝게)
  r0: "#3b0d2c", r1: "#931a45", r2: "#e2263f", r3: "#ff6a4f", r4: "#ffbf94",
  // 주황
  o0: "#4a1428", o1: "#b33a1c", o2: "#f2731f", o3: "#ffae3c", o4: "#ffe48c",
  // 노랑 · 금
  y0: "#4c1f1c", y1: "#c0651a", y2: "#fbbd2a", y3: "#ffdd45", y4: "#fff7b0",
  // 초록
  g0: "#11303f", g1: "#18684f", g2: "#2ea447", g3: "#86d44a", g4: "#dcf48e",
  // 청록
  t0: "#102746", t1: "#11677b", t2: "#18aa99", t3: "#5ce0b2", t4: "#cbfad6",
  // 하늘
  s0: "#171f4f", s1: "#1e54a6", s2: "#2896de", s3: "#7ad4f5", s4: "#d9fbff",
  // 파랑
  b0: "#1b1447", b1: "#2e2f9f", b2: "#3f66e2", b3: "#76aaff", b4: "#c6e3ff",
  // 보라
  p0: "#2a1044", p1: "#5b2698", p2: "#9447d8", p3: "#cf82f0", p4: "#f7cbf3",
  // 분홍
  k0: "#460f34", k1: "#a42263", k2: "#ea508f", k3: "#ff92ad", k4: "#ffd8d0",
  // 갈색 · 나무
  n0: "#2d1323", n1: "#66301f", n2: "#a3592a", n3: "#d89346", n4: "#f4cc7b",
  // 크림 · 종이 (외곽은 갈색 n0 · n1)
  c1: "#c98d57", c2: "#eec389", c3: "#fbe7b8", c4: "#fffaea",
  // 쇠 · 회색
  a0: "#1c1a31", a1: "#464a6e", a2: "#7e88a8", a3: "#bec7d9", a4: "#eef2f6",
  w: "#ffffff",
};

// ───────────────────────── 그림 ─────────────────────────
// pal 의 값은 ART_PALETTE 이름. 지도는 위에서 아래로 16줄, 줄마다 16칸.

const SPRITES = {
  // ── 아이템 ──
  "xp-potion": {
    pal: { o: "s0", D: "s1", B: "s2", L: "s3", w: "w", d: "g1", G: "g2", g: "g3", c: "n2", C: "n3" },
    map: [
      "............oo..",
      "...........oCCo.",
      "..........oCcCCo",
      ".........owLccco",
      "....oooooBBLBco.",
      "..ooLwLLBBBBBo..",
      ".oLwLBBBBBBDo...",
      ".oLggGwGGdDo....",
      "oLggGwwwGdDo....",
      "oLgGwwwwwdDo....",
      "oLgGGwwwddDo....",
      "oLgGGwwwddDo....",
      ".oLGGwwwdDo.....",
      ".oBBdGddDDo.....",
      "..ooBBDDoo......",
      "....oooo........",
    ],
  },
  "attend-potion": {
    pal: { o: "s0", D: "s1", B: "s3", L: "s4", w: "w", d: "b1", G: "b2", g: "b3", c: "n2", C: "n3" },
    map: [
      "............oo..",
      "...........oCCo.",
      "..........oCcCCo",
      ".........owLccco",
      "....oooooBBLBco.",
      "..ooLwLLBBBBBo..",
      ".oLwLBBBBBBDo...",
      ".oLggGwGGdDo....",
      "oLggGwwwGdDo....",
      "oLgGwwwwwdDo....",
      "oLgGGwwwddDo....",
      "oLgGGwwwddDo....",
      ".oLGGwwwdDo.....",
      ".oBBdGddDDo.....",
      "..ooBBDDoo......",
      "....oooo........",
    ],
  },
  "music-ticket": {
    pal: { o: "k0", l: "k1", m: "k2", L: "k3", h: "k4", w: "w" },
    map: [
      "................",
      "................",
      "................",
      ".lllllllllllllo.",
      "lhLLLLLLLLLlLLLo",
      "lLmmmmmwwmmmmmmo",
      "lLmmmmmwmwmlmmmo",
      ".lmmmmmwmmmmmmo.",
      ".lmmmwwwmmmlmmo.",
      "lLmmmwwwmmmmmmmo",
      "lLmmmmmmmmmlmmmo",
      "ollllllllllllllo",
      ".oooooooooooooo.",
      "................",
      "................",
      "................",
    ],
  },
  "slowmode-off": {
    pal: { N: "n0", C: "c3", c: "c2", o: "o0", l: "o1", m: "o2", L: "o3", x: "r0", R: "r2", w: "w" },
    map: [
      "NN...NN.........",
      "NN...NN..ooooo..",
      "NCN.NCN.oLLLLmo.",
      ".NCNCN.oLLlllmmo",
      ".NCCCN.oLlLmmlmo",
      ".NCCcN.oLlmlmlmo",
      ".NCCcN.oLlmlllmo",
      ".NCCcN.oLmlxxmmo",
      ".NCCcNNNoxRRRRx.",
      "NCCcccccxRRwwRRx",
      "NcccccccRRRwwwRR",
      "NccccccxRwwRwwwR",
      ".NNNNNNxRwwwRwwR",
      "........RRwwwRRR",
      "........xRRwwRRx",
      ".........xRRRRx.",
    ],
  },

  // ── 시간대 ──
  "owl-charm": {
    pal: { o: "p0", l: "p1", m: "p2", L: "p3", h: "p4", Y: "y3", y: "y2", B: "o2", b: "o1", w: "w" },
    map: [
      ".oo..........oo.",
      ".oLo........omo.",
      ".oLLoooooooommo.",
      ".oLmmmmmmmmmmlo.",
      ".oLmYYmmmmYYmlo.",
      ".oLYwoYmmYwoYlo.",
      ".oLYooYBBYooYlo.",
      ".oLmyymbbmyymlo.",
      ".oLmmhhhhhhmmlo.",
      ".olmlLlLLlLlmlo.",
      ".olmLlLLLLlLmlo.",
      ".olmLLLLLLLLmlo.",
      ".olmLLlLLlLLmlo.",
      "..olmLLllLLmlo..",
      "...ooBBooBBoo...",
      ".....oo..oo.....",
    ],
  },
  "early-bird": {
    pal: { o: "s0", l: "s1", m: "s2", L: "s3", W: "w", B: "o3", b: "o2", K: "k0", P: "k2", Q: "k3" },
    map: [
      "................",
      "................",
      "......oooo......",
      "....ooWWLLoo....",
      "...oLLLLLLLmo...",
      "..oLWoLLLmmmmo..",
      ".KKLooLooommmoo.",
      "KBBmmmolllommolo",
      ".KbWWmollllomolo",
      "KQPKWWmollllooo.",
      "KQPKWWWmooolo...",
      "KQPKoWWmmllo....",
      ".KQPKoooooo.....",
      ".KQPKbbKKbbK....",
      "..KK.KK..KK.....",
      "................",
    ],
  },
  "lunch-box": {
    pal: { o: "r0", l: "r1", m: "r2", L: "r3", W: "w", Y: "y3", y: "y2", d: "y1", G: "g3", g: "g2" },
    map: [
      "................",
      ".oooooooooooooo.",
      "oLLLLLLLLLLLLLmo",
      "oLmmmmmmmmmmmmlo",
      "oLmWWWWlYYdYYmlo",
      "oLmWWWWlYYdYymlo",
      "oLmWWWWlYydYymlo",
      "oLmWLmWlyydyymlo",
      "oLmWmmWllllllmlo",
      "oLmWWWWlWLGGgmlo",
      "oLmWWWWlLLGggmlo",
      "oLmWWWWlLmlglmlo",
      "oLmmmmmmmmmmmmlo",
      "omlllllllllllllo",
      ".oooooooooooooo.",
      "................",
    ],
  },
  radio: {
    pal: { o: "t0", l: "t1", m: "t2", L: "t3", h: "t4", c: "c3", R: "r2", a: "a2", A: "a3" },
    map: [
      "...ooooooo..ooo.",
      "..oAAAAAAAo.oRo.",
      "..oAoooooao.oao.",
      "..oAo...oao.oao.",
      ".oooooooooooooo.",
      "ohLLLLLLLLLLLLlo",
      "oLmmmmmmmmmmmmlo",
      "oLmoooommooooolo",
      "oLoccccomocRcolo",
      "oLollllomocRcolo",
      "oLoccccomooooolo",
      "oLollllommmmmmlo",
      "oLmoooommAamAalo",
      "oLmmmmmmmaamaalo",
      "ollllllllllllllo",
      ".oooooooooooooo.",
    ],
  },
  "night-lantern": {
    pal: { o: "p0", D: "p1", M: "p2", L: "p3", h: "p4", Y: "y2", y: "y3", W: "y4", F: "o2", w: "w" },
    map: [
      "......oooo......",
      ".....o....o.....",
      ".....o....o.....",
      "....oooooooo....",
      "...ohLMMMMMDo...",
      "..ohLMMMMMMMDo..",
      ".oLLMMMMMMMMMDo.",
      ".oooooooooooooo.",
      "..oLwyyyFyyYDo..",
      "..oLwyyFFyyYDo..",
      "..oLyyFFWFyYDo..",
      "..oLyyFWwFyYDo..",
      "..oLYyyFFyYYDo..",
      ".oooooooooooooo.",
      ".oLMMMMMMMMMMDo.",
      "..oooooooooooo..",
    ],
  },

  // ── 요일 ──
  "weekend-sword": {
    pal: { o: "a0", O: "y0", L: "a4", A: "a3", a: "a2", B: "b2", b: "b1", G: "y3", g: "y2", W: "y4" },
    map: [
      "..............o.",
      "............ooAo",
      "...........oLAAo",
      "..........oLAAao",
      ".........oLABao.",
      "........oLABao..",
      "....OO.oLABao...",
      "...OgGOLABao....",
      "....OgGABao.....",
      ".....OgGao......",
      "....oBbgGO......",
      "...oBboOgGO.....",
      "..OBbo..OO......",
      ".OWGO...........",
      ".OGgO...........",
      "..OO............",
    ],
  },
  "friday-fire": {
    pal: { o: "r0", d: "r1", R: "r2", r: "r3", O: "o2", P: "o3", Y: "y3", W: "y4", w: "w" },
    map: [
      ".......oo.......",
      "......orRo......",
      "......orRo...oo.",
      ".....orRRRo.oRo.",
      ".oo..orRPRoorRo.",
      ".oro.orRPORROdo.",
      ".orRooRPOOROOdo.",
      ".orRRRRPOOOORdo.",
      "orRRPOOYOOOORRdo",
      "orRPOOYYYOOORRdo",
      "orRPOYYYYYOOORdo",
      "orRPYYWWWYYOORdo",
      "orROYWWwwWYYORdo",
      ".oROYYWWWWYYOdo.",
      "..oROOYYYYOOdo..",
      "...oooooooooo...",
    ],
  },
  "monday-vaccine": {
    pal: { o: "a0", w: "w", h: "g4", g: "g3", G: "g2", d: "g1", a: "a2", A: "a3", k: "k2", K: "k3" },
    map: [
      "..........oo....",
      ".........okKo...",
      ".......o..okKo..",
      "......oAo.oAkKo.",
      "......oaAoAaokKo",
      "......ogaAao.oo.",
      ".....owhgaAo....",
      "....owggGGaAo...",
      "...ogggGGdoao...",
      "..ogggGGdo.o....",
      "..oggGGdo.......",
      ".oAAGGdo........",
      ".oAaodo.........",
      "oAoo.o..........",
      "Ao..............",
      "o...............",
    ],
  },
  "wednesday-coffee": {
    pal: { o: "k0", D: "k1", M: "k2", L: "k3", H: "k4", c: "n1", C: "n2", e: "n3", w: "w" },
    map: [
      "................",
      ".oooooooooo.....",
      "oLccccccccMo....",
      "oLeCCCCCCCMo....",
      "oHLLLLLLLLMo....",
      "oLHMMMMMMMDoooo.",
      "oLMMMMMMMMDoMMDo",
      "oLMMMMMMMMDooMDo",
      "oLMMwwMwwMDooMDo",
      "oLMMwwwwwMDooMDo",
      "oLMMMwwwMMDooMDo",
      "oLMMMMwMMMDoMDDo",
      "oLMMMMMMMDDoooo.",
      "oLMMMMMMMDDo....",
      ".oDDDDDDDDo.....",
      "..oooooooo......",
    ],
  },

  // ── 채널 ──
  "scrim-mic": {
    pal: { o: "a0", d: "y1", y: "y2", Y: "y3", H: "y4", w: "w", D: "a1", A: "a2", L: "a3", R: "r2" },
    map: [
      ".....oooooo.....",
      "....oHwYYdyo....",
      "...oHwYYYdyyo...",
      "...owYddddddo...",
      "...oYYdYYdyyo...",
      "...oYYdYYdyyo...",
      "...oddddddddo...",
      "...oyydyydyyo...",
      "....oydyydyo....",
      "....oDDDDDDo....",
      ".....oLAADo.....",
      ".....oLAADo.....",
      ".....oLRADo.....",
      ".....oLAADo.....",
      ".....oLAADo.....",
      "......oooo......",
    ],
  },
  "chat-megaphone": {
    pal: { o: "t0", D: "t1", M: "t2", L: "t3", H: "t4", w: "w", Y: "y3", y: "y2", d: "y1" },
    map: [
      "............ooo.",
      "..........ooHLMo",
      "........ooLLwLMo",
      "......ooLLMMwLMo",
      "....ooLLMMMMwLMo",
      ".oooLLMMMMMMwLMo",
      "oYYoLMMMMMMMHLMo",
      "oYyoMMMMMMMMHLMo",
      "oyyoMMMMMMMMHLMo",
      "odyoMMMMMMMMHLMo",
      ".oooDDMMMMMMHLMo",
      "....oYyDMMMMLMDo",
      "....oYyoDDMMLMDo",
      "....oYyoooDDLMDo",
      "....oydo..ooLMDo",
      ".....oo.....ooo.",
    ],
  },
  "gamer-headset": {
    pal: { o: "a0", l: "a1", D: "a1", m: "a2", B: "a2", L: "a3", W: "a4", e: "g4", g: "g3", G: "g2" },
    map: [
      "................",
      ".....lllllo.....",
      "...llmmmmmmoo...",
      "..lmWLLLLLLLmo..",
      ".lmmmmoooommmmo.",
      ".lmmoo....oommo.",
      ".lmmo......ommo.",
      "lmDDDo....oDDDDo",
      "lmeDDo....oDDeDo",
      "lmgDDo....oDDgDo",
      "lmgDDo....oDDgDo",
      "lmGDDo....oDDGDo",
      "omGDDo....oDDGDo",
      ".oDDBoooo..oDDo.",
      "..oooBBBGo..oo..",
      ".....oooo.......",
    ],
  },
  "music-earbuds": {
    pal: { o: "a0", l: "a1", K: "a1", d: "a3", W: "a4", w: "w", P: "k2", p: "k1", Q: "k3" },
    map: [
      "........PPP.....",
      "........P.P.....",
      "........P.......",
      "......QPP.......",
      "......Pp........",
      "..lll......lll..",
      ".lwwWo....lwwWo.",
      "lwwwWWo..lwwwWWo",
      "lwwWKdo..lwKwWdo",
      "lwWWKdo..lWKWWdo",
      ".lWddo....lWddo.",
      ".lWdo......lWdo.",
      ".lWdo......lWdo.",
      ".lWdo......lWdo.",
      ".oddo......oddo.",
      "..oo........oo..",
    ],
  },

  // ── 출석 ──
  "attend-stamp": {
    pal: { o: "n0", d: "n1", m: "n2", L: "n3", h: "n4", Y: "y3", R: "r2", r: "r1", C: "c4", c: "c3" },
    map: [
      ".....ooooooooooo",
      ".....oCCCCCCCCco",
      ".....oCCCCRRRRco",
      ".....oCCCRRRRCRo",
      "...ooooCCRCRCRRo",
      "..ohhLLoCRRCRRRo",
      ".ohLLLmdoRRRRRro",
      ".oLmmmddoCRRRRco",
      "..omdddoCCCCCCco",
      "...oYYoCCCCCCCco",
      ".oooLdooocccccco",
      "ohLLLLLLmooooooo",
      "oLmmmmmmdo......",
      "oddddddddo......",
      ".oRRRRRro.......",
      "..oooooo........",
    ],
  },
  "month-trophy": {
    pal: { o: "y0", d: "y1", m: "y2", L: "y3", h: "y4", w: "w", P: "p0", q: "p1", Q: "p2", R: "p3" },
    map: [
      "..oooooooooooo..",
      "ooohhhhLLLLLmooo",
      "oLoLwLLmhmmmdomo",
      "oLoLwLmhhhmmdomo",
      ".oLoLLmmhmmdomo.",
      "..oLoLmmmmdomo..",
      "...ooLmmmddoo...",
      ".....oLmmdo.....",
      "......oLdo......",
      ".....ooLdoo.....",
      "....oLLmmmdo....",
      "...PPPPPPPPPP...",
      "..PRRRRRRRRRqP..",
      "..PRQQLLLLQQqP..",
      "..PQQQQQQQQQqP..",
      "...PPPPPPPPPP...",
    ],
  },
  "hundred-cake": {
    pal: { o: "n0", Y: "y4", F: "o3", W: "w", S: "s3", K: "k3", k: "k2", C: "c3", c: "c2", R: "r2" },
    map: [
      ".......oo.......",
      "......oYFo......",
      "......oYFo......",
      "....oo.oo.oo....",
      "...oWRoWSoWRo...",
      "...oRRoWSoRRo...",
      "..oWKKKKKKKKko..",
      "..oKKKKKKKKKko..",
      "..oCkCCkCCCkco..",
      "..oCCCCCCCCcco..",
      ".oooooooooooooo.",
      "oWKKKKKKKKKKKKko",
      "oKKKKKKKKKKKKKko",
      "oCkCCkCCCkCCkCco",
      "oCCCCCCCCCCCCcco",
      ".oooooooooooooo.",
    ],
  },
  "veteran-mic": {
    pal: { o: "a0", d: "a1", m: "a2", L: "a3", h: "a4", W: "w", H: "y4", Y: "y3", y: "y1", R: "r2" },
    map: [
      ".....oooooo.....",
      "....ohWLLLmo....",
      "...ohLLLLLLmo...",
      "...oLddddddmo...",
      "..oohLLLLLLmoo..",
      ".oHoLddddddmoyo.",
      ".oYohLLLLLLmoyo.",
      ".oYoLddddddmoyo.",
      ".oYohLLLLLLmoyo.",
      ".oYoLddddddmoyo.",
      ".oYomLLLLLLdoyo.",
      ".oYooooooooooyo.",
      "..oHYYYYYYYyyo..",
      "...ooooLdoooo...",
      "...ohLLRRLLmo...",
      "....oooooooo....",
    ],
  },
  "allnight-headset": {
    pal: { o: "p0", l: "p1", d: "p1", m: "p2", L: "p3", h: "p4", C: "k3", K: "k2", Y: "y3" },
    map: [
      "................",
      "................",
      ".....lllllo.....",
      "...llhLLLLmoo...",
      "..lLLLmmmmmmdo..",
      ".lLmmoooooommdo.",
      ".lLmo......omdo.",
      ".lLmo......omdo.",
      "lllllo....oooooo",
      "lLmmCo.YY.oCmmdo",
      "lLmmCoYY..oCmmdo",
      "lLmmCoYY..oCmmdo",
      "oLmmKoYY..oKmmdo",
      "odddKo.YY.oKdddo",
      ".ooooo....ooooo.",
      "................",
    ],
  },
  "morning-hello": {
    pal: { o: "o0", r: "o2", R: "o3", L: "y3", H: "y4", K: "k3", q: "g0", l: "g1", g: "g2", G: "g3" },
    map: [
      ".......oo.......",
      "......oRro......",
      ".oo...oRro...oo.",
      "oRRo..oooo..oRro",
      ".oRrooHHLLooRro.",
      "..oooHoLLoLooo..",
      "...oHLoLLoLLo...",
      ".oooLLLLLLLrooo.",
      "oRRoKKoLLoKKoRRo",
      "orroLLLooLrrorro",
      ".ooLLLLLLLrrroo.",
      "..oLLqqqqqqrro..",
      "..qqqGGGGGGqqq..",
      "qqGGGggggggGGGqq",
      "qGllllllllllllGq",
      ".qqqqqqqqqqqqqq.",
    ],
  },
  "growth-serum": {
    pal: { o: "s0", B: "s2", L: "s3", w: "w", d: "k1", G: "k2", c: "n2", C: "n3", e: "g2", f: "g3" },
    map: [
      ".....ooo....oo..",
      "....offfoo.oCCo.",
      ".....oeffeoCcCCo",
      "......oeeowLccco",
      "....oooooBBLBco.",
      "..ooLwLLBBBBBo..",
      ".oLwLBBBBBBBo...",
      ".oLGGGwGGdBo....",
      "oLGGGwwwGdBo....",
      "oLGGwwwwwdBo....",
      "oLGGGwwwddBo....",
      "oLGGGwwwddBo....",
      ".oLGGwwwdBo.....",
      ".oBBdGddBBo.....",
      "..ooBBBBoo......",
      "....oooo........",
    ],
  },

  // ── 묶음 ──
  "allround-set": {
    pal: { o: "n0", d: "n1", N: "n2", L: "n3", h: "n4", e: "g1", g: "g2", G: "g3", Y: "y3", W: "y4" },
    map: [
      "......oooo......",
      "......o..o......",
      "....oooooooo....",
      "...ohhLLLLLNo...",
      "..ohLLNNNNNNdo..",
      ".ohLNNNNNNNNNdo.",
      ".oLNNNNNNNNNddo.",
      "..ooNNNNNNNNoo..",
      ".oGGNdooooNdggo.",
      "oGGGNdGGGGNdgggo",
      "oGGGWYGGGGWYgggo",
      "oGGGNdGGGGNdgggo",
      "oGGGNdGGGGNdgggo",
      "oGGGNdGGGGNdgggo",
      ".oeeeeeeeeeeeeo.",
      "..oooooooooooo..",
    ],
  },
  "starter-pack": {
    pal: { O: "k0", d: "k1", R: "k2", L: "k3", h: "k4", q: "t0", y: "t1", Y: "t2", U: "t3", H: "t4" },
    map: [
      ".qqq........qqq.",
      "qHUUq......qUUYq",
      "qUyyUq....qUyyYq",
      ".qUyyUqqqqUyyYq.",
      "..qqqqUHUYqqqq..",
      ".OOOOOOqqOOOOOO.",
      "OhLLLLLUYLLLLLdO",
      "OLRRRRRUYRRRRRdO",
      ".OOOOOOqqOOOOOO.",
      ".OdddddyydddddO.",
      ".OLRRRRUYRRRRdO.",
      ".OLRRRRUYRRRRdO.",
      ".OLRRRRUYRRRRdO.",
      ".OLRRRRUYRRRRdO.",
      ".OdddddyydddddO.",
      "..OOOOOqqOOOOO..",
    ],
  },
  "night-set": {
    pal: { O: "b0", d: "b1", R: "b2", L: "b3", h: "b4", q: "y0", y: "y1", Y: "y2", U: "y3", H: "y4" },
    map: [
      "...OOOO..OOOO...",
      "..OhLLROOLLRdO..",
      "..OLRRRRRRRRdO..",
      "...ORRRRRRRdO...",
      "..qUUYYYYYYYyq..",
      "...OLRRYyRRdO...",
      "..OLRRUUYRRRdO..",
      ".OLRRUHRRRRRRdO.",
      "OLRRUHYRRRRURRdO",
      "OLRRUUYRRRUHURdO",
      "OLRRUYYRRRRURRdO",
      "OLRRRYYRRRRRRRdO",
      "OLRRRRYYyRRRRddO",
      ".ORRRRRRRRRRddO.",
      "..OddddddddddO..",
      "...OOOOOOOOOO...",
    ],
  },

  // ── 효과 ──
  "forge-coupon": {
    pal: { O: "o0", d: "o1", Y: "o2", U: "o3", h: "o4", M: "a2", L: "a3", N: "n2", H: "n3", w: "w" },
    map: [
      "................",
      "................",
      ".OOOOOOOOOOOOOO.",
      "OhUUUUUUUUUdUUUO",
      "OUYOOOOOOYYYUUdO",
      "OUOwLLLLMOYdUUdO",
      "OUOMMMMMMOYYUUdO",
      ".OYOOHNOOYYdUUO.",
      ".OYYOHNOYYYYUUO.",
      "OUYYOHNOYYYdUUdO",
      "OUYYOHNOYYYYUUdO",
      "OUYYOHNOYYYdUUdO",
      "OddddOOddddddddO",
      ".OOOOOOOOOOOOOO.",
      "................",
      "................",
    ],
  },
  "cashback-coin": {
    pal: { O: "y0", d: "y1", Y: "y2", U: "y3", H: "y4", L: "g3", G: "g2", g: "g1" },
    map: [
      ".....OOOOOO.....",
      "...OOHHUUUUOO...",
      "..OHUYYYYYYUUO..",
      ".OHYYYYYLYYYYdO.",
      ".OUYYYYYGGYYYdO.",
      "OUYYYYLLGGGYYYdO",
      "OUYYYLGGGGgdYYdO",
      "OUYYLGddGgddYYdO",
      "OUYYLGYYgddYYYdO",
      "OUYYLGYYYdLgYYdO",
      "OUYYLGYYYYGgdYdO",
      ".OUYYGGGGGgdddO.",
      ".OUYYYggggddYdO.",
      "..OddYYddddddO..",
      "...OOddddddOO...",
      ".....OOOOOO.....",
    ],
  },
  "binok-pickaxe": {
    pal: { O: "t0", d: "t1", G: "t2", T: "t3", w: "w", D: "n1", M: "n2", L: "n3", y: "y2", Y: "y3" },
    map: [
      ".....OOOOO......",
      "..OOOTwwTTOO....",
      ".OTwwGGGGGTTO...",
      "..OddddGGGGGTO..",
      "...OOOOddOdGGTO.",
      ".......OOYOdGTO.",
      ".......OYYyOdGTO",
      "......OLYyOdGGTO",
      ".....OLMDOOdGGTO",
      "....OLMDO..OdGGO",
      "...OLMDO...OdGGO",
      "..OLMDO....OdGO.",
      ".OOODO.....OdGO.",
      "OYyOO.......OdO.",
      "OyyO.........O..",
      ".OO.............",
    ],
  },
  "promo-badge": {
    pal: { O: "s0", d: "s1", S: "s2", L: "s3", h: "s4", y: "y1", Y: "y2", U: "y3", H: "y4" },
    map: [
      "..OOOOOOOOOOOO..",
      ".OhLLLLLLLLLLdO.",
      ".OLSSSSHUSSSSdO.",
      ".OLSSSUYYUSSSdO.",
      ".OLSSUYyyYUSSdO.",
      ".OLSUYySSyYUSdO.",
      ".OLUYySUUSyYUdO.",
      ".OLYySUYYUSyYdO.",
      ".OLySUYyyYUSydO.",
      ".OLSUYySSyYUSdO.",
      "..OSYySSSSyYdO..",
      "...OySSSSSSyO...",
      "....OSSSSSdO....",
      ".....OSSSdO.....",
      "......OddO......",
      ".......OO.......",
    ],
  },
  "quest-scroll": {
    pal: { O: "n0", n: "n1", N: "n2", c: "c1", C: "c2", L: "c3", h: "c4", r: "r1", R: "r2", k: "r3" },
    map: [
      ".OOOOOOOOOOOOOO.",
      "ONhLLLLLLLLLLCNO",
      "OnccccccccccccnO",
      ".OOCCCCCCCCCCOO.",
      "..OhLLLLLLLLCO..",
      "..OLnnnnnnnLCO..",
      "..OLLLLLLLLLCO..",
      "..OLnnnnLLLLCO..",
      "..OLLLLkRLLLCO..",
      "..OLLLkRRrLLCO..",
      "..OLLLRRrrLLCO..",
      "..OCCCCrrCCCcO..",
      ".OhLLLLLLLLLLCO.",
      "ONCCCCCCCCCCCcNO",
      "OnccccccccccccnO",
      ".OOOOOOOOOOOOOO.",
    ],
  },
  "pass-rocket": {
    pal: { O: "a0", h: "a4", L: "a3", M: "a2", k: "r3", R: "r2", r: "r1", S: "s2", F: "o2", Y: "y3" },
    map: [
      ".......OO.......",
      "......OkRO......",
      ".....OkRRrO.....",
      "....OkRRRRrO....",
      "....OhLLLLMO....",
      "....OhLOOLMO....",
      "....OhOhSOMO....",
      "...OOhOSSOMOO...",
      "..OkOhLOOLMOrO..",
      ".OkROhLLLLMORrO.",
      ".OkROkRRRRrORrO.",
      ".OrrOOOOOOOOrrO.",
      "..OO.OFYYFO.OO..",
      ".....OFYYFO.....",
      "......OFFO......",
      ".......OO.......",
    ],
  },
  "cooldown-hourglass": {
    pal: { o: "n0", l: "n1", d: "n1", N: "n2", L: "n3", h: "n4", w: "w", Y: "y3", y: "y2", G: "s4" },
    map: [
      "..lllllllllllo..",
      ".lhLLLLLLLLLLNo.",
      ".lNNNNNNNNNNNdo.",
      "..oooooooooooo..",
      "...owYYYYYYGo...",
      "....oYYYYYyo....",
      ".....oYYYyo.....",
      "......oYyo......",
      "......oYyo......",
      ".....oGYyGo.....",
      "....oGwYyGGo....",
      "...oYYYYYyyyo...",
      "..oooooooooooo..",
      ".lhLLLLLLLLLLNo.",
      ".oNNNNNNNNNNNdo.",
      "..oooooooooooo..",
    ],
  },
  "soundproof-booth": {
    pal: { o: "p0", L: "p3", m: "p2", d: "p1", A: "a3", a: "a2", D: "a1", x: "r0", R: "r2", w: "w" },
    map: [
      "..........xxxx..",
      ".ooooooooxRRRRx.",
      "oLLLLLLLxRwRRwRx",
      "oLmmoommxRRwwRRx",
      "oLmoAaomxRRwwRRx",
      "oLmmoommxRwRRwRx",
      "oLmmoooomxRRRRx.",
      "oLmoAAAaomxxxx..",
      "oLoAAaaaDodo....",
      "oLoAaooaDodo....",
      "oLoAaooaDodo....",
      "oLoaaaaDDodo....",
      "oLmoaDDDomdo....",
      "oLmmoooommdo....",
      "oddddddddddo....",
      ".oooooooooo.....",
    ],
  },
  "streak-shield": {
    pal: { o: "b0", B: "b3", b: "b2", d: "b1", H: "y4", Y: "y3", y: "y2", T: "y1", R: "r2", O: "o2" },
    map: [
      ".oooooooooooooo.",
      "oHYYYYYYYYYYYYyo",
      "oYBbbbbbbbbbbdyo",
      "oYBbbbbRRbbbbdyo",
      "oYbbbRbRRbRbbdyo",
      "oYbbbRRRRRRbbdyo",
      "oYbbRRROORRRbdyo",
      "oYbbRROOOORRbdyo",
      "oYbbROOYYOORbdyo",
      ".oYbROYYYYORdyo.",
      ".oYbROYHHYORdyo.",
      "..oybROYYORdTo..",
      "...oybROORdTo...",
      "....oybdddTo....",
      ".....ooyToo.....",
      ".......oo.......",
    ],
  },
  "jackpot-slot": {
    pal: { o: "r0", d: "r1", m: "r2", L: "r3", h: "r4", Y: "y3", y: "y2", T: "y1", w: "w", A: "a3" },
    map: [
      "...ooooooo...oo.",
      "..oYwYYYYyo.ohLo",
      ".ooooooooooooLmo",
      "oLLLLLLLLLLmooo.",
      "oooooooooooooAo.",
      "owwwAwwwAwwwoAo.",
      "ommmAmmmAmmmoAo.",
      "owwmAwwmAwwmoAo.",
      "owmwAwmwAwmwoAo.",
      "owmwAwmwAwmwoAo.",
      "owwwAwwwAwwwoAo.",
      "ooooooooooooooo.",
      "oLmmmmmmmmmdo...",
      "oLmTYYYYYTmdo...",
      "odddddddddddo...",
      ".ooooooooooo....",
    ],
  },
  "lucky-clover": {
    pal: { o: "g0", l: "g1", m: "g2", L: "g3", h: "g4", w: "w", Y: "y3" },
    map: [
      "....lll.llo...Y.",
      "...lLLLoLLmo.YwY",
      "...lLLmhmmlo..Y.",
      ".ll.lLmhmll.ll..",
      "lLLl.lmmll.lLmo.",
      "lLLml.lll.lLLmo.",
      "lLmmml.l.lLLmmo.",
      ".ohhmlllllmhho..",
      "lLmmll.lmlmmmlo.",
      "lLmll.lllmlmllo.",
      "omll.lLmmlmlllo.",
      ".oo.lLLhmllmoo..",
      "...lLLmhmmlomo..",
      "...lmmlomlloomo.",
      "....ooo.ooo..o..",
      "................",
    ],
  },
  "party-together": {
    pal: { o: "a0", A: "a2", a: "a1", w: "w", k: "k3", Y: "o3", R: "r2", S: "s2", K: "k2", h: "k4" },
    map: [
      "..ooo......ooo..",
      ".oAaao....oAaao.",
      "oAaaaao..oAaaaao",
      "oawwwao..oawwwao",
      "owowowo..owowowo",
      "okwYwko..okwYwko",
      "oRRRRRo..oSSSSSo",
      "oawwooo..ooowwao",
      "oawohKKooKKKowao",
      "oawoKKKKKKKKowao",
      "oawwoKKKKKKowwao",
      "oawwwoKKKKowwwao",
      "oawwwaoKKoawwwao",
      ".oawao.oo.oawao.",
      "oYYoYYo..oYYoYYo",
      ".oo.oo....oo.oo.",
    ],
  },
  "welcome-fairy": {
    pal: { o: "p0", Y: "y3", y: "y2", K: "k4", k: "k3", P: "k2", p: "k1", S: "s3", s: "s2", w: "w" },
    map: [
      "......oooo......",
      ".....owYYYo.....",
      ".oo.oYYYYYyo.oo.",
      "oSSooYKKKKyooSSo",
      "oSwSoYoKKoyoSwSo",
      "oSSSoYkKKkyoSSso",
      ".oSSSoKKKKoSSso.",
      "..oSSokPPpoSso..",
      ".oSSSokPPpoSSso.",
      "oSwSokPPPPpoSwso",
      ".oSSokPPPPpoSso.",
      ".oookPPPPPPpooo.",
      "...oppppppppo...",
      "...oooooooooo...",
      ".....oKooKo.....",
      "......o..o......",
    ],
  },
  "card-skin": {
    pal: { o: "p0", B: "p1", Y: "y3", y: "y2", d: "y1", f: "p1", s: "s3", k: "k3", r: "r2", w: "w" },
    map: [
      ".....ooooooooo..",
      "....oBByBByBBBo.",
      "...oooooooooBBo.",
      "..fYYYYYYYYyoBo.",
      "..fYyfwskfydoyo.",
      "..fYfwskfffdoBo.",
      "..fYwskffffdoBo.",
      "..fYskfYfffdoyo.",
      "..fYkfYwyffdoBo.",
      "..fYfYkrrdfdoBo.",
      "..fYfyrrrdfdoyo.",
      "..fYffyrdfsdoBo.",
      "..fYfffdfskdoBo.",
      "..fYyfffskydoo..",
      "..oyddddddddo...",
      "...ooooooooo....",
    ],
  },
  "profile-badge": {
    pal: { o: "t0", T: "t3", t: "t2", D: "t1", x: "y0", H: "y4", Y: "y3", y: "y2", M: "y1", w: "w" },
    map: [
      ".ooooo....ooooo.",
      ".oTwDo....oTwDo.",
      ".oTwDo....oTwDo.",
      "..oTwDo..oTwDo..",
      "..oTwDo..oTwDo..",
      "...oTwDooTwDo...",
      "...oTwxxxxwDo...",
      "....xxwYYyxx....",
      "....xHYYYYyx....",
      "...xHYYttYyyx...",
      "...xYttttttyx...",
      "...xYYttttyMx...",
      "...xYYtyytyMx...",
      "....xYyyyyMx....",
      "....xxyMMMxx....",
      "......xxxx......",
    ],
  },
  "xp-bolt": {
    pal: { o: "y0", l: "y1", d: "y1", T: "y2", Y: "y3", h: "y4", w: "w" },
    map: [
      "........llllo...",
      ".......lhhYYdo..",
      "......lhYYYdo...",
      ".....lhYYYdo....",
      "....lhYYYdo.....",
      "...lhwYYdoooo...",
      "..lhYYYYYTTTdo..",
      "...ooohYYTTdo...",
      ".....lYYTTdo....",
      "....lYYTTdo.....",
      "...lYYTdoo......",
      "...lYTdo........",
      "..lYTdo.........",
      "..oTdo..........",
      "...oo...........",
      "................",
    ],
  },

  // ── 시즌 ──
  "sky-island": {
    pal: { O: "a0", h: "g3", g: "g2", d: "g1", t: "n2", T: "n1", r: "a2", R: "a1", W: "s4", w: "s3" },
    map: [
      "..OOOOO.........",
      ".OhhhggOO.......",
      "OhhhgggghO......",
      "OhhgggggdO......",
      ".OggggdddO......",
      "..OOOtTOOO......",
      ".OOOOtTOOOOOOOO.",
      "OhhhhhhhhhWWWWwO",
      "OgggggggggdOWwwO",
      "OgtttgttttTOWwWO",
      "OTTTTTTTTTTOWwwO",
      ".OrrrrrrrRROWwwO",
      "..OrrrrRRRROWWwO",
      "...OrrrRRROOWwwO",
      "....ORRRO..OWOWO",
      ".....OOO....O.O.",
    ],
  },
  compass: {
    pal: { o: "n0", a: "y3", b: "y2", c: "y1", d: "w", e: "r3", f: "r2", g: "c3", h: "s3", i: "s2" },
    map: [
      ".....oabbco.....",
      "....oaooooco....",
      ".....obbcco.....",
      "...ooaaaaaaoo...",
      "..oaabbbbccbbo..",
      ".oabbddefggccbo.",
      ".oabdddefgggcbo.",
      "oabdddeeffgggcco",
      "oabddgbabcgggcco",
      "oabcggbbccggccco",
      "oabggghhiigggcco",
      "oacgggghiggggcco",
      ".oacggghigggcco.",
      ".obccccccccccco.",
      "..obbbccccccco..",
      "...oooooooooo...",
    ],
  },
  airship: {
    pal: { o: "n0", a: "r2", b: "r3", c: "w", d: "c3", e: "r1", f: "y2", g: "a3", h: "n3", i: "n2" },
    map: [
      "................",
      "oo..ooooooooo...",
      "abooccbbbcccboo.",
      "oabcccbbbccdaaao",
      ".obcccbaadddaaeo",
      ".offfffffffffffo",
      "oaadddaaedddeeeo",
      "eeooddeeedddeoo.",
      "oo..ooooooooo...",
      "...o.ooooooo....",
      "..ogofffffffo...",
      "..ogghhiiiiio...",
      "..ogooiiiiio....",
      "...o..ooooo.....",
      "................",
      "................",
    ],
  },
  portal: {
    pal: { o: "a0", d: "a1", m: "a2", l: "a3", Y: "y3", P: "p1", p: "p2", q: "p3", t: "t3", w: "w" },
    map: [
      "....oooooooo....",
      "..oollmYYmmdoo..",
      ".olllmdYYdmmmdo.",
      "ollmdmoooomdmmdo",
      "ollmooPPPPoommdo",
      "olmoPPpppPPPomdo",
      "olmoPpqqqppPomdo",
      "oddopqtttqpPoddo",
      "olmopqtwwtqpomdo",
      "olmopqttwtqpomdo",
      "oddoPpqttqqpoddo",
      "olmoPPpqqqpPomdo",
      "olmoPPPpppPPomdo",
      "oddoPPPPPPPPoddo",
      "olllmmmmmmmmmmdo",
      "oooooooooooooooo",
    ],
  },
  "pioneer-flag": {
    pal: { o: "n0", Y: "y3", h: "r3", R: "r2", r: "r1", w: "w", G: "g3", g: "g2", N: "n2", n: "n1" },
    map: [
      "...oooooooooooo.",
      "...owohhhYhhhho.",
      "...oYoRYYYYYro..",
      "...oYoRRYYYro...",
      "...oYoRRYrYrro..",
      "...oYorrrrrrrro.",
      "...oYoooooooooo.",
      "...oYo..........",
      "..ooYooooooooo..",
      ".oGGGGGGGGGGGGo.",
      "oGGggggggggggggo",
      "ogNgggNggNgggNgo",
      ".oNNNNnNNNNnnno.",
      "..ooNNnNNnnnoo..",
      "....ooNnnnoo....",
      "......oooo......",
    ],
  },
  "sky-seed": {
    pal: { O: "g0", d: "g1", m: "g2", L: "g3", h: "g4", P: "o0", q: "o1", r: "o2", y: "o3", b: "s3" },
    map: [
      "..........OOOO..",
      ".........OhLLmO.",
      "..OOOO..OhLLLmmO",
      ".OhLLmO.OLLLmmdO",
      "OhLLLmmOOLLmmddO",
      "OLLLmmmdOLmmddO.",
      ".OmmmmddOmddOO..",
      "..OOOOOmdOOO....",
      ".PPPPPPPPPPPPPP.",
      ".PyyyyyyyyyrrqP.",
      ".PrrrrrrrrrrqqP.",
      "..PqqqqqqqqqqP..",
      "..PybbbbbbbbqP..",
      "..PyrrrrrrrrqP..",
      "...PyrrrrrrqP...",
      "...PPPPPPPPPP...",
    ],
  },
  "cloud-candy": {
    pal: { O: "k0", d: "k1", m: "k2", L: "k3", h: "k4", B: "s2", S: "s3", W: "s4", c: "c3", n: "c1" },
    map: [
      "........OOOO....",
      ".......OhhLLO...",
      "....OOOOhLLLmO..",
      "...OhhhdhLLmmmO.",
      "...OhLLLdLLmmddO",
      "...OhLLmdmmdddO.",
      "..OhLLmmdmdWWSSO",
      "..OhLmmdWWSSSSBO",
      "..OLLmdWSSSSSBBO",
      "..OLmmdSSSSSBBBO",
      "...OmdSSSSBBBBO.",
      "...OcnOOOOOOOO..",
      "..OcnO..........",
      ".OcnO...........",
      "OcnO............",
      "OOO.............",
    ],
  },
  "wind-pinwheel": {
    pal: { O: "p0", w: "w", a: "k3", b: "k2", c: "k1", H: "s4", L: "s3", M: "s2", Y: "y3", y: "y1" },
    map: [
      "..OOOOOOO.......",
      ".OwwwwwwO....OO.",
      ".ObwaaaaO...OMLO",
      "..ObaaaaO..OMLLO",
      "...ObaaaO.OMLLLO",
      "....OOaaO.OLLLLO",
      "......OaOOLLLLLO",
      "OOOOOOOYYLLLLLLO",
      "OwHHHHHYyOOOOOOO",
      "OwHHHHOObO......",
      "OwHHHOyObbOO....",
      "OwHHLOyObbbcO...",
      "OwwLOYyObbbbcO..",
      "OwLOOYyObbbbbcO.",
      ".OO.OYyObbbbbbO.",
      "....OOOOOOOOOO..",
    ],
  },
  "star-shard": {
    pal: { O: "y0", d: "y1", y: "y2", Y: "y3", h: "y4", P: "p0", k: "k3", p: "p2", s: "s3" },
    map: [
      "..........O.....",
      ".........OhO....",
      "........OhYyO...",
      ".....OOOOhYyOOOO",
      ".....OhhYYYYYyyO",
      "......OhYYYYyyO.",
      "....PPPOYYYyydO.",
      "...PkkkkOYyyydO.",
      "..PkkpppOyyddyO.",
      ".PkppssOyydOdddO",
      "PkpssPPOddO.OOdO",
      "PkpsP...OO....OO",
      "PkpP............",
      "PkP.............",
      "PP..............",
      "................",
    ],
  },
};

// ───────────────────────── 내보내기 ─────────────────────────

// 한 줄에서 같은 색이 이어지는 칸을 묶고, 바로 윗줄과 모양이 같으면 세로로 늘린다 — key 마다 한 번만 만든다
const bodies = new Map();
function bodyOf(key) {
  if (bodies.has(key)) return bodies.get(key);
  const s = SPRITES[key];
  let out = "";
  if (s) {
    const open = new Map(); // "x,w,색" → 아직 닫지 않은 rect
    const done = [];
    s.map.forEach((row, y) => {
      const runs = [];
      for (let x = 0; x < row.length; ) {
        const c = row[x];
        let e = x + 1;
        while (e < row.length && row[e] === c) e++;
        if (c !== ".") runs.push([x, e - x, ART_PALETTE[s.pal[c]]]);
        x = e;
      }
      const seen = new Set();
      for (const [x, w, fill] of runs) {
        const id = `${x},${w},${fill}`;
        seen.add(id);
        const r = open.get(id);
        if (r && r.y + r.h === y) r.h++;
        else {
          if (r) done.push(r);
          open.set(id, { x, y, w, h: 1, fill });
        }
      }
      for (const [id, r] of open) {
        if (seen.has(id)) continue;
        done.push(r);
        open.delete(id);
      }
    });
    done.push(...open.values());
    done.sort((a, b) => a.y - b.y || a.x - b.x);
    out = done.map((r) => `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" fill="${r.fill}"/>`).join("");
  }
  bodies.set(key, out);
  return out;
}

// svg 안쪽(rect 들)만 — React 는 <svg viewBox="0 0 16 16"> 에 이걸 넣는다.
//    예전 호출의 둘째 인자(uid)는 그대로 받아도 되지만 쓰지 않는다(그라데이션이 없어 id 가 필요 없다)
export function itemArtBody(key) {
  if (!isArtKey(key)) return "";
  return bodyOf(key);
}

// 완성된 SVG 문자열 — 서버 · node 스크립트 · 이미지 만들기에서 쓴다. size 는 16 의 배수가 가장 또렷하다({ uid } 는 무시)
export function itemArtSvg(key, { size = 48 } = {}) {
  const body = itemArtBody(key);
  if (!body) return "";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="${size}" height="${size}" shape-rendering="crispEdges" aria-hidden="true">${body}</svg>`;
}
